//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetshoesService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoRplEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity.RPL")]
    public partial class ProdutoRplEN : object
    {
        
        private string AcaoField;
        
        private string CodigoBarrasField;
        
        private int CodigoClasseField;
        
        private int CodigoDepartamentoField;
        
        private string CodigoFabricanteField;
        
        private int CodigoFamiliaField;
        
        private int CodigoGrupoField;
        
        private string CodigoMarcaField;
        
        private string CodigoNCMField;
        
        private string CodigoProdutoField;
        
        private int CodigoProdutoAbacosField;
        
        private int CodigoProdutoAvoField;
        
        private string CodigoProdutoPaiField;
        
        private int CodigoProdutoPaiAbacosField;
        
        private int CodigoSubGrupoField;
        
        private int CodigoTipoProdutoField;
        
        private double ComprimentoField;
        
        private string CorField;
        
        private string DescricaoField;
        
        private string DescricaoClasseField;
        
        private string DescricaoComplementar1Field;
        
        private string DescricaoDepartamentoField;
        
        private string DescricaoFamiliaField;
        
        private string DescricaoGrupoField;
        
        private string DescricaoMarcaField;
        
        private string DescricaoNotaFiscalField;
        
        private string DescricaoSubGrupoField;
        
        private string DescricaoTipoProdutoField;
        
        private string DescritorPreDefinido1Field;
        
        private string DescritorPreDefinido2Field;
        
        private double EspessuraField;
        
        private string IdentificaCorSaborField;
        
        private string IdentificadorProdutoField;
        
        private int KeyField;
        
        private double LarguraField;
        
        private NetshoesService.ValorAtributo[] ListaAtributosField;
        
        private NetshoesService.Categoria[] ListaCategoriasField;
        
        private NetshoesService.Loja[] ListaLojasField;
        
        private NetshoesService.Subloja[] ListaSublojasField;
        
        private string NomeProdutoField;
        
        private string NomeProdutoReduzidoField;
        
        private double PesoField;
        
        private string ProdutoAvoField;
        
        private string ProdutoKitField;
        
        private string ProdutoTemFilhosField;
        
        private string ProtocoloProdutoField;
        
        private int QtdePorEmbalagemField;
        
        private int ReposicaoAutomaticaField;
        
        private string SaborField;
        
        private string TamanhoField;
        
        private string VoltagemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acao
        {
            get
            {
                return this.AcaoField;
            }
            set
            {
                this.AcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoBarras
        {
            get
            {
                return this.CodigoBarrasField;
            }
            set
            {
                this.CodigoBarrasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoClasse
        {
            get
            {
                return this.CodigoClasseField;
            }
            set
            {
                this.CodigoClasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoDepartamento
        {
            get
            {
                return this.CodigoDepartamentoField;
            }
            set
            {
                this.CodigoDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoFabricante
        {
            get
            {
                return this.CodigoFabricanteField;
            }
            set
            {
                this.CodigoFabricanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoFamilia
        {
            get
            {
                return this.CodigoFamiliaField;
            }
            set
            {
                this.CodigoFamiliaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoGrupo
        {
            get
            {
                return this.CodigoGrupoField;
            }
            set
            {
                this.CodigoGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoMarca
        {
            get
            {
                return this.CodigoMarcaField;
            }
            set
            {
                this.CodigoMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoNCM
        {
            get
            {
                return this.CodigoNCMField;
            }
            set
            {
                this.CodigoNCMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProduto
        {
            get
            {
                return this.CodigoProdutoField;
            }
            set
            {
                this.CodigoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoProdutoAbacos
        {
            get
            {
                return this.CodigoProdutoAbacosField;
            }
            set
            {
                this.CodigoProdutoAbacosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoProdutoAvo
        {
            get
            {
                return this.CodigoProdutoAvoField;
            }
            set
            {
                this.CodigoProdutoAvoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProdutoPai
        {
            get
            {
                return this.CodigoProdutoPaiField;
            }
            set
            {
                this.CodigoProdutoPaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoProdutoPaiAbacos
        {
            get
            {
                return this.CodigoProdutoPaiAbacosField;
            }
            set
            {
                this.CodigoProdutoPaiAbacosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoSubGrupo
        {
            get
            {
                return this.CodigoSubGrupoField;
            }
            set
            {
                this.CodigoSubGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoProduto
        {
            get
            {
                return this.CodigoTipoProdutoField;
            }
            set
            {
                this.CodigoTipoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Comprimento
        {
            get
            {
                return this.ComprimentoField;
            }
            set
            {
                this.ComprimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cor
        {
            get
            {
                return this.CorField;
            }
            set
            {
                this.CorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoClasse
        {
            get
            {
                return this.DescricaoClasseField;
            }
            set
            {
                this.DescricaoClasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoComplementar1
        {
            get
            {
                return this.DescricaoComplementar1Field;
            }
            set
            {
                this.DescricaoComplementar1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoDepartamento
        {
            get
            {
                return this.DescricaoDepartamentoField;
            }
            set
            {
                this.DescricaoDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoFamilia
        {
            get
            {
                return this.DescricaoFamiliaField;
            }
            set
            {
                this.DescricaoFamiliaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoGrupo
        {
            get
            {
                return this.DescricaoGrupoField;
            }
            set
            {
                this.DescricaoGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoMarca
        {
            get
            {
                return this.DescricaoMarcaField;
            }
            set
            {
                this.DescricaoMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoNotaFiscal
        {
            get
            {
                return this.DescricaoNotaFiscalField;
            }
            set
            {
                this.DescricaoNotaFiscalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoSubGrupo
        {
            get
            {
                return this.DescricaoSubGrupoField;
            }
            set
            {
                this.DescricaoSubGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoTipoProduto
        {
            get
            {
                return this.DescricaoTipoProdutoField;
            }
            set
            {
                this.DescricaoTipoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescritorPreDefinido1
        {
            get
            {
                return this.DescritorPreDefinido1Field;
            }
            set
            {
                this.DescritorPreDefinido1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescritorPreDefinido2
        {
            get
            {
                return this.DescritorPreDefinido2Field;
            }
            set
            {
                this.DescritorPreDefinido2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Espessura
        {
            get
            {
                return this.EspessuraField;
            }
            set
            {
                this.EspessuraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificaCorSabor
        {
            get
            {
                return this.IdentificaCorSaborField;
            }
            set
            {
                this.IdentificaCorSaborField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorProduto
        {
            get
            {
                return this.IdentificadorProdutoField;
            }
            set
            {
                this.IdentificadorProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Largura
        {
            get
            {
                return this.LarguraField;
            }
            set
            {
                this.LarguraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetshoesService.ValorAtributo[] ListaAtributos
        {
            get
            {
                return this.ListaAtributosField;
            }
            set
            {
                this.ListaAtributosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetshoesService.Categoria[] ListaCategorias
        {
            get
            {
                return this.ListaCategoriasField;
            }
            set
            {
                this.ListaCategoriasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetshoesService.Loja[] ListaLojas
        {
            get
            {
                return this.ListaLojasField;
            }
            set
            {
                this.ListaLojasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetshoesService.Subloja[] ListaSublojas
        {
            get
            {
                return this.ListaSublojasField;
            }
            set
            {
                this.ListaSublojasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto
        {
            get
            {
                return this.NomeProdutoField;
            }
            set
            {
                this.NomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProdutoReduzido
        {
            get
            {
                return this.NomeProdutoReduzidoField;
            }
            set
            {
                this.NomeProdutoReduzidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Peso
        {
            get
            {
                return this.PesoField;
            }
            set
            {
                this.PesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdutoAvo
        {
            get
            {
                return this.ProdutoAvoField;
            }
            set
            {
                this.ProdutoAvoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdutoKit
        {
            get
            {
                return this.ProdutoKitField;
            }
            set
            {
                this.ProdutoKitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdutoTemFilhos
        {
            get
            {
                return this.ProdutoTemFilhosField;
            }
            set
            {
                this.ProdutoTemFilhosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProtocoloProduto
        {
            get
            {
                return this.ProtocoloProdutoField;
            }
            set
            {
                this.ProtocoloProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdePorEmbalagem
        {
            get
            {
                return this.QtdePorEmbalagemField;
            }
            set
            {
                this.QtdePorEmbalagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReposicaoAutomatica
        {
            get
            {
                return this.ReposicaoAutomaticaField;
            }
            set
            {
                this.ReposicaoAutomaticaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sabor
        {
            get
            {
                return this.SaborField;
            }
            set
            {
                this.SaborField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tamanho
        {
            get
            {
                return this.TamanhoField;
            }
            set
            {
                this.TamanhoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Voltagem
        {
            get
            {
                return this.VoltagemField;
            }
            set
            {
                this.VoltagemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValorAtributo", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity")]
    public partial class ValorAtributo : object
    {
        
        private string NomeField;
        
        private string ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity")]
    public partial class Categoria : object
    {
        
        private int CodigoCategoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCategoria
        {
            get
            {
                return this.CodigoCategoriaField;
            }
            set
            {
                this.CodigoCategoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loja", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity")]
    public partial class Loja : object
    {
        
        private int CodigoDepartamentoLojaField;
        
        private int CodigoLojaField;
        
        private string NomeDepartamentoLojaField;
        
        private string NomeLojaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoDepartamentoLoja
        {
            get
            {
                return this.CodigoDepartamentoLojaField;
            }
            set
            {
                this.CodigoDepartamentoLojaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLoja
        {
            get
            {
                return this.CodigoLojaField;
            }
            set
            {
                this.CodigoLojaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeDepartamentoLoja
        {
            get
            {
                return this.NomeDepartamentoLojaField;
            }
            set
            {
                this.NomeDepartamentoLojaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeLoja
        {
            get
            {
                return this.NomeLojaField;
            }
            set
            {
                this.NomeLojaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subloja", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity")]
    public partial class Subloja : object
    {
        
        private int CodigoSubLojaField;
        
        private string NomeSubLojaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoSubLoja
        {
            get
            {
                return this.CodigoSubLojaField;
            }
            set
            {
                this.CodigoSubLojaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeSubLoja
        {
            get
            {
                return this.NomeSubLojaField;
            }
            set
            {
                this.NomeSubLojaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaRplEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity.RPL")]
    public partial class CategoriaRplEN : object
    {
        
        private string AcaoField;
        
        private int ClassificacaoField;
        
        private int CodigoCategoriaPaiIDField;
        
        private int CodigoCategoriaProdutoField;
        
        private int CodigoCategoriaProdutoPaiField;
        
        private int CodigoInterfaceField;
        
        private string CodigoTipoField;
        
        private int CodigoTipoAbacosField;
        
        private System.DateTime DataConfirmacaoField;
        
        private System.DateTime DataDesativacaoField;
        
        private System.DateTime DataLogField;
        
        private int KeyField;
        
        private string NomeField;
        
        private string NomeTipoField;
        
        private int OrdemSequencialField;
        
        private string ProtocoloCategoriaProdutoField;
        
        private bool VisivelNaLojaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acao
        {
            get
            {
                return this.AcaoField;
            }
            set
            {
                this.AcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Classificacao
        {
            get
            {
                return this.ClassificacaoField;
            }
            set
            {
                this.ClassificacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCategoriaPaiID
        {
            get
            {
                return this.CodigoCategoriaPaiIDField;
            }
            set
            {
                this.CodigoCategoriaPaiIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCategoriaProduto
        {
            get
            {
                return this.CodigoCategoriaProdutoField;
            }
            set
            {
                this.CodigoCategoriaProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoCategoriaProdutoPai
        {
            get
            {
                return this.CodigoCategoriaProdutoPaiField;
            }
            set
            {
                this.CodigoCategoriaProdutoPaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoInterface
        {
            get
            {
                return this.CodigoInterfaceField;
            }
            set
            {
                this.CodigoInterfaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipo
        {
            get
            {
                return this.CodigoTipoField;
            }
            set
            {
                this.CodigoTipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoAbacos
        {
            get
            {
                return this.CodigoTipoAbacosField;
            }
            set
            {
                this.CodigoTipoAbacosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataConfirmacao
        {
            get
            {
                return this.DataConfirmacaoField;
            }
            set
            {
                this.DataConfirmacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataDesativacao
        {
            get
            {
                return this.DataDesativacaoField;
            }
            set
            {
                this.DataDesativacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataLog
        {
            get
            {
                return this.DataLogField;
            }
            set
            {
                this.DataLogField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTipo
        {
            get
            {
                return this.NomeTipoField;
            }
            set
            {
                this.NomeTipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdemSequencial
        {
            get
            {
                return this.OrdemSequencialField;
            }
            set
            {
                this.OrdemSequencialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProtocoloCategoriaProduto
        {
            get
            {
                return this.ProtocoloCategoriaProdutoField;
            }
            set
            {
                this.ProtocoloCategoriaProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisivelNaLoja
        {
            get
            {
                return this.VisivelNaLojaField;
            }
            set
            {
                this.VisivelNaLojaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarcaRplEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity.RPL")]
    public partial class MarcaRplEN : object
    {
        
        private string AcaoField;
        
        private string AtivoField;
        
        private string CodigoExternoMarcaField;
        
        private int CodigoInterfaceField;
        
        private int CodigoMarcaField;
        
        private System.DateTime DataConfirmacaoField;
        
        private System.DateTime DataLogField;
        
        private int KeyField;
        
        private string NomeField;
        
        private string ProtocoloMarcaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acao
        {
            get
            {
                return this.AcaoField;
            }
            set
            {
                this.AcaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ativo
        {
            get
            {
                return this.AtivoField;
            }
            set
            {
                this.AtivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoExternoMarca
        {
            get
            {
                return this.CodigoExternoMarcaField;
            }
            set
            {
                this.CodigoExternoMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoInterface
        {
            get
            {
                return this.CodigoInterfaceField;
            }
            set
            {
                this.CodigoInterfaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMarca
        {
            get
            {
                return this.CodigoMarcaField;
            }
            set
            {
                this.CodigoMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataConfirmacao
        {
            get
            {
                return this.DataConfirmacaoField;
            }
            set
            {
                this.DataConfirmacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataLog
        {
            get
            {
                return this.DataLogField;
            }
            set
            {
                this.DataLogField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProtocoloMarca
        {
            get
            {
                return this.ProtocoloMarcaField;
            }
            set
            {
                this.ProtocoloMarcaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrecoRplEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity.RPL")]
    public partial class PrecoRplEN : object
    {
        
        private string Categoriak__BackingFieldField;
        
        private int CodigoInterfacek__BackingFieldField;
        
        private int CodigoListak__BackingFieldField;
        
        private int CodigoProdutoAbacosk__BackingFieldField;
        
        private string CodigoProdutoPaik__BackingFieldField;
        
        private string CodigoProdutok__BackingFieldField;
        
        private System.DateTime DataConfirmacaok__BackingFieldField;
        
        private System.DateTime DataInicioPromocaok__BackingFieldField;
        
        private System.DateTime DataLogk__BackingFieldField;
        
        private System.DateTime DataTerminoPromocaok__BackingFieldField;
        
        private string IdSellerk__BackingFieldField;
        
        private int Keyk__BackingFieldField;
        
        private string Moedak__BackingFieldField;
        
        private string NomeListak__BackingFieldField;
        
        private string NomeLojistak__BackingFieldField;
        
        private int PersonalizacaoTipok__BackingFieldField;
        
        private double PrecoPromocionalk__BackingFieldField;
        
        private double PrecoTabelak__BackingFieldField;
        
        private string ProdutoTipok__BackingFieldField;
        
        private string ProtocoloPrecok__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Categoria>k__BackingField", IsRequired=true)]
        public string Categoriak__BackingField
        {
            get
            {
                return this.Categoriak__BackingFieldField;
            }
            set
            {
                this.Categoriak__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CodigoInterface>k__BackingField", IsRequired=true)]
        public int CodigoInterfacek__BackingField
        {
            get
            {
                return this.CodigoInterfacek__BackingFieldField;
            }
            set
            {
                this.CodigoInterfacek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CodigoLista>k__BackingField", IsRequired=true)]
        public int CodigoListak__BackingField
        {
            get
            {
                return this.CodigoListak__BackingFieldField;
            }
            set
            {
                this.CodigoListak__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CodigoProdutoAbacos>k__BackingField", IsRequired=true)]
        public int CodigoProdutoAbacosk__BackingField
        {
            get
            {
                return this.CodigoProdutoAbacosk__BackingFieldField;
            }
            set
            {
                this.CodigoProdutoAbacosk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CodigoProdutoPai>k__BackingField", IsRequired=true)]
        public string CodigoProdutoPaik__BackingField
        {
            get
            {
                return this.CodigoProdutoPaik__BackingFieldField;
            }
            set
            {
                this.CodigoProdutoPaik__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CodigoProduto>k__BackingField", IsRequired=true)]
        public string CodigoProdutok__BackingField
        {
            get
            {
                return this.CodigoProdutok__BackingFieldField;
            }
            set
            {
                this.CodigoProdutok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataConfirmacao>k__BackingField", IsRequired=true)]
        public System.DateTime DataConfirmacaok__BackingField
        {
            get
            {
                return this.DataConfirmacaok__BackingFieldField;
            }
            set
            {
                this.DataConfirmacaok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataInicioPromocao>k__BackingField", IsRequired=true)]
        public System.DateTime DataInicioPromocaok__BackingField
        {
            get
            {
                return this.DataInicioPromocaok__BackingFieldField;
            }
            set
            {
                this.DataInicioPromocaok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataLog>k__BackingField", IsRequired=true)]
        public System.DateTime DataLogk__BackingField
        {
            get
            {
                return this.DataLogk__BackingFieldField;
            }
            set
            {
                this.DataLogk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataTerminoPromocao>k__BackingField", IsRequired=true)]
        public System.DateTime DataTerminoPromocaok__BackingField
        {
            get
            {
                return this.DataTerminoPromocaok__BackingFieldField;
            }
            set
            {
                this.DataTerminoPromocaok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IdSeller>k__BackingField", IsRequired=true)]
        public string IdSellerk__BackingField
        {
            get
            {
                return this.IdSellerk__BackingFieldField;
            }
            set
            {
                this.IdSellerk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Key>k__BackingField", IsRequired=true)]
        public int Keyk__BackingField
        {
            get
            {
                return this.Keyk__BackingFieldField;
            }
            set
            {
                this.Keyk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Moeda>k__BackingField", IsRequired=true)]
        public string Moedak__BackingField
        {
            get
            {
                return this.Moedak__BackingFieldField;
            }
            set
            {
                this.Moedak__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<NomeLista>k__BackingField", IsRequired=true)]
        public string NomeListak__BackingField
        {
            get
            {
                return this.NomeListak__BackingFieldField;
            }
            set
            {
                this.NomeListak__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<NomeLojista>k__BackingField", IsRequired=true)]
        public string NomeLojistak__BackingField
        {
            get
            {
                return this.NomeLojistak__BackingFieldField;
            }
            set
            {
                this.NomeLojistak__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PersonalizacaoTipo>k__BackingField", IsRequired=true)]
        public int PersonalizacaoTipok__BackingField
        {
            get
            {
                return this.PersonalizacaoTipok__BackingFieldField;
            }
            set
            {
                this.PersonalizacaoTipok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PrecoPromocional>k__BackingField", IsRequired=true)]
        public double PrecoPromocionalk__BackingField
        {
            get
            {
                return this.PrecoPromocionalk__BackingFieldField;
            }
            set
            {
                this.PrecoPromocionalk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PrecoTabela>k__BackingField", IsRequired=true)]
        public double PrecoTabelak__BackingField
        {
            get
            {
                return this.PrecoTabelak__BackingFieldField;
            }
            set
            {
                this.PrecoTabelak__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProdutoTipo>k__BackingField", IsRequired=true)]
        public string ProdutoTipok__BackingField
        {
            get
            {
                return this.ProdutoTipok__BackingFieldField;
            }
            set
            {
                this.ProdutoTipok__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProtocoloPreco>k__BackingField", IsRequired=true)]
        public string ProtocoloPrecok__BackingField
        {
            get
            {
                return this.ProtocoloPrecok__BackingFieldField;
            }
            set
            {
                this.ProtocoloPrecok__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyPair", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.WCFProduto.ClassMap")]
    public partial class KeyPair : object
    {
        
        private string IdEntityField;
        
        private int KeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEntity
        {
            get
            {
                return this.IdEntityField;
            }
            set
            {
                this.IdEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrecoEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Produto.Entity")]
    public partial class PrecoEN : object
    {
        
        private int KeyField;
        
        private double PrecoField;
        
        private string SkuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Preco
        {
            get
            {
                return this.PrecoField;
            }
            set
            {
                this.PrecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku
        {
            get
            {
                return this.SkuField;
            }
            set
            {
                this.SkuField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NetshoesService.IProdutoWCF")]
    public interface IProdutoWCF
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ListarProdutos", ReplyAction="http://tempuri.org/IProdutoWCF/ListarProdutosResponse")]
        System.Threading.Tasks.Task<NetshoesService.ListarProdutosResponse> ListarProdutosAsync(NetshoesService.ListarProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ListarCategorias", ReplyAction="http://tempuri.org/IProdutoWCF/ListarCategoriasResponse")]
        System.Threading.Tasks.Task<NetshoesService.ListarCategoriasResponse> ListarCategoriasAsync(NetshoesService.ListarCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ListarMarcas", ReplyAction="http://tempuri.org/IProdutoWCF/ListarMarcasResponse")]
        System.Threading.Tasks.Task<NetshoesService.ListarMarcasResponse> ListarMarcasAsync(NetshoesService.ListarMarcasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ListarPrecos", ReplyAction="http://tempuri.org/IProdutoWCF/ListarPrecosResponse")]
        System.Threading.Tasks.Task<NetshoesService.ListarPrecosResponse> ListarPrecosAsync(NetshoesService.ListarPrecosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ListarPrecosStep", ReplyAction="http://tempuri.org/IProdutoWCF/ListarPrecosStepResponse")]
        System.Threading.Tasks.Task<NetshoesService.ListarPrecosStepResponse> ListarPrecosStepAsync(NetshoesService.ListarPrecosStepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarDataEnvioPrecosStep", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarDataEnvioPrecosStepResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarDataEnvioPrecosStepResponse> ConfirmarDataEnvioPrecosStepAsync(NetshoesService.ConfirmarDataEnvioPrecosStepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarPrecosStep", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarPrecosStepResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarPrecosStepResponse> ConfirmarPrecosStepAsync(NetshoesService.ConfirmarPrecosStepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoProduto", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoProdutoResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoProdutoResponse> ConfirmarRecebimentoProdutoAsync(NetshoesService.ConfirmarRecebimentoProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoCategoria", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoCategoriaResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoCategoriaResponse> ConfirmarRecebimentoCategoriaAsync(NetshoesService.ConfirmarRecebimentoCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoMarca", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoMarcaResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoMarcaResponse> ConfirmarRecebimentoMarcaAsync(NetshoesService.ConfirmarRecebimentoMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoPreco", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoPrecoResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoPrecoResponse> ConfirmarRecebimentoPrecoAsync(NetshoesService.ConfirmarRecebimentoPrecoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoProdutoLista", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoProdutoListaResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoProdutoListaResponse> ConfirmarRecebimentoProdutoListaAsync(NetshoesService.ConfirmarRecebimentoProdutoListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoCategoriaLista", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoCategoriaListaResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoCategoriaListaResponse> ConfirmarRecebimentoCategoriaListaAsync(NetshoesService.ConfirmarRecebimentoCategoriaListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoMarcaLista", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoMarcaListaResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoMarcaListaResponse> ConfirmarRecebimentoMarcaListaAsync(NetshoesService.ConfirmarRecebimentoMarcaListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoPrecoLista", ReplyAction="http://tempuri.org/IProdutoWCF/ConfirmarRecebimentoPrecoListaResponse")]
        System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoPrecoListaResponse> ConfirmarRecebimentoPrecoListaAsync(NetshoesService.ConfirmarRecebimentoPrecoListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/PrecoLojaOnLine", ReplyAction="http://tempuri.org/IProdutoWCF/PrecoLojaOnLineResponse")]
        System.Threading.Tasks.Task<NetshoesService.PrecoLojaOnLineResponse> PrecoLojaOnLineAsync(NetshoesService.PrecoLojaOnLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoWCF/TipoCompilacao", ReplyAction="http://tempuri.org/IProdutoWCF/TipoCompilacaoResponse")]
        System.Threading.Tasks.Task<NetshoesService.TipoCompilacaoResponse> TipoCompilacaoAsync(NetshoesService.TipoCompilacaoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarProdutos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarProdutosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        public ListarProdutosRequest()
        {
        }
        
        public ListarProdutosRequest(string identificacaoLoja, string chaveIdentificacao)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarProdutosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarProdutosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesService.ProdutoRplEN[] ListarProdutosResult;
        
        public ListarProdutosResponse()
        {
        }
        
        public ListarProdutosResponse(NetshoesService.ProdutoRplEN[] ListarProdutosResult)
        {
            this.ListarProdutosResult = ListarProdutosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCategorias", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarCategoriasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        public ListarCategoriasRequest()
        {
        }
        
        public ListarCategoriasRequest(string identificacaoLoja, string chaveIdentificacao)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCategoriasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarCategoriasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesService.CategoriaRplEN[] ListarCategoriasResult;
        
        public ListarCategoriasResponse()
        {
        }
        
        public ListarCategoriasResponse(NetshoesService.CategoriaRplEN[] ListarCategoriasResult)
        {
            this.ListarCategoriasResult = ListarCategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarMarcas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarMarcasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        public ListarMarcasRequest()
        {
        }
        
        public ListarMarcasRequest(string identificacaoLoja, string chaveIdentificacao)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarMarcasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarMarcasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesService.MarcaRplEN[] ListarMarcasResult;
        
        public ListarMarcasResponse()
        {
        }
        
        public ListarMarcasResponse(NetshoesService.MarcaRplEN[] ListarMarcasResult)
        {
            this.ListarMarcasResult = ListarMarcasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPrecos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPrecosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        public ListarPrecosRequest()
        {
        }
        
        public ListarPrecosRequest(string identificacaoLoja, string chaveIdentificacao)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPrecosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPrecosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesService.PrecoRplEN[] ListarPrecosResult;
        
        public ListarPrecosResponse()
        {
        }
        
        public ListarPrecosResponse(NetshoesService.PrecoRplEN[] ListarPrecosResult)
        {
            this.ListarPrecosResult = ListarPrecosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPrecosStep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPrecosStepRequest
    {
        
        public ListarPrecosStepRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPrecosStepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPrecosStepResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesService.PrecoRplEN[] ListarPrecosStepResult;
        
        public ListarPrecosStepResponse()
        {
        }
        
        public ListarPrecosStepResponse(NetshoesService.PrecoRplEN[] ListarPrecosStepResult)
        {
            this.ListarPrecosStepResult = ListarPrecosStepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarDataEnvioPrecosStep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarDataEnvioPrecosStepRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idLogPreco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string produto;
        
        public ConfirmarDataEnvioPrecosStepRequest()
        {
        }
        
        public ConfirmarDataEnvioPrecosStepRequest(int idLogPreco, string produto)
        {
            this.idLogPreco = idLogPreco;
            this.produto = produto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarDataEnvioPrecosStepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarDataEnvioPrecosStepResponse
    {
        
        public ConfirmarDataEnvioPrecosStepResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarPrecosStep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarPrecosStepRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idLogPreco;
        
        public ConfirmarPrecosStepRequest()
        {
        }
        
        public ConfirmarPrecosStepRequest(int idLogPreco)
        {
            this.idLogPreco = idLogPreco;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarPrecosStepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarPrecosStepResponse
    {
        
        public ConfirmarPrecosStepResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoProduto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoProdutoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int keyProduto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string codigoProduto;
        
        public ConfirmarRecebimentoProdutoRequest()
        {
        }
        
        public ConfirmarRecebimentoProdutoRequest(string identificacaoLoja, string chaveIdentificacao, int keyProduto, string codigoProduto)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.keyProduto = keyProduto;
            this.codigoProduto = codigoProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoProdutoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoProdutoResponse
    {
        
        public ConfirmarRecebimentoProdutoResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoCategoria", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoCategoriaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int keyCategoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int codigoCategoriaProduto;
        
        public ConfirmarRecebimentoCategoriaRequest()
        {
        }
        
        public ConfirmarRecebimentoCategoriaRequest(string identificacaoLoja, string chaveIdentificacao, int keyCategoria, int codigoCategoriaProduto)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.keyCategoria = keyCategoria;
            this.codigoCategoriaProduto = codigoCategoriaProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoCategoriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoCategoriaResponse
    {
        
        public ConfirmarRecebimentoCategoriaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoMarca", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoMarcaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int keyMarca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int codigoMarca;
        
        public ConfirmarRecebimentoMarcaRequest()
        {
        }
        
        public ConfirmarRecebimentoMarcaRequest(string identificacaoLoja, string chaveIdentificacao, int keyMarca, int codigoMarca)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.keyMarca = keyMarca;
            this.codigoMarca = codigoMarca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoMarcaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoMarcaResponse
    {
        
        public ConfirmarRecebimentoMarcaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoPreco", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoPrecoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int keyPreco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string codigoProduto;
        
        public ConfirmarRecebimentoPrecoRequest()
        {
        }
        
        public ConfirmarRecebimentoPrecoRequest(string identificacaoLoja, string chaveIdentificacao, int keyPreco, string codigoProduto)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.keyPreco = keyPreco;
            this.codigoProduto = codigoProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoPrecoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoPrecoResponse
    {
        
        public ConfirmarRecebimentoPrecoResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoProdutoLista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoProdutoListaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public NetshoesService.KeyPair[] listChaves;
        
        public ConfirmarRecebimentoProdutoListaRequest()
        {
        }
        
        public ConfirmarRecebimentoProdutoListaRequest(string identificacaoLoja, string chaveIdentificacao, NetshoesService.KeyPair[] listChaves)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.listChaves = listChaves;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoProdutoListaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoProdutoListaResponse
    {
        
        public ConfirmarRecebimentoProdutoListaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoCategoriaLista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoCategoriaListaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public NetshoesService.KeyPair[] listChaves;
        
        public ConfirmarRecebimentoCategoriaListaRequest()
        {
        }
        
        public ConfirmarRecebimentoCategoriaListaRequest(string identificacaoLoja, string chaveIdentificacao, NetshoesService.KeyPair[] listChaves)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.listChaves = listChaves;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoCategoriaListaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoCategoriaListaResponse
    {
        
        public ConfirmarRecebimentoCategoriaListaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoMarcaLista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoMarcaListaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public NetshoesService.KeyPair[] listChaves;
        
        public ConfirmarRecebimentoMarcaListaRequest()
        {
        }
        
        public ConfirmarRecebimentoMarcaListaRequest(string identificacaoLoja, string chaveIdentificacao, NetshoesService.KeyPair[] listChaves)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.listChaves = listChaves;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoMarcaListaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoMarcaListaResponse
    {
        
        public ConfirmarRecebimentoMarcaListaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoPrecoLista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoPrecoListaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public NetshoesService.KeyPair[] listChaves;
        
        public ConfirmarRecebimentoPrecoListaRequest()
        {
        }
        
        public ConfirmarRecebimentoPrecoListaRequest(string identificacaoLoja, string chaveIdentificacao, NetshoesService.KeyPair[] listChaves)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.listChaves = listChaves;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmarRecebimentoPrecoListaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConfirmarRecebimentoPrecoListaResponse
    {
        
        public ConfirmarRecebimentoPrecoListaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrecoLojaOnLine", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PrecoLojaOnLineRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] ListaSKU;
        
        public PrecoLojaOnLineRequest()
        {
        }
        
        public PrecoLojaOnLineRequest(string identificacaoLoja, string chaveIdentificacao, string[] ListaSKU)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.ListaSKU = ListaSKU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrecoLojaOnLineResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PrecoLojaOnLineResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesService.PrecoEN[] PrecoLojaOnLineResult;
        
        public PrecoLojaOnLineResponse()
        {
        }
        
        public PrecoLojaOnLineResponse(NetshoesService.PrecoEN[] PrecoLojaOnLineResult)
        {
            this.PrecoLojaOnLineResult = PrecoLojaOnLineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TipoCompilacao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TipoCompilacaoRequest
    {
        
        public TipoCompilacaoRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TipoCompilacaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TipoCompilacaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TipoCompilacaoResult;
        
        public TipoCompilacaoResponse()
        {
        }
        
        public TipoCompilacaoResponse(string TipoCompilacaoResult)
        {
            this.TipoCompilacaoResult = TipoCompilacaoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IProdutoWCFChannel : NetshoesService.IProdutoWCF, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ProdutoWCFClient : System.ServiceModel.ClientBase<NetshoesService.IProdutoWCF>, NetshoesService.IProdutoWCF
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProdutoWCFClient() : 
                base(ProdutoWCFClient.GetDefaultBinding(), ProdutoWCFClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProdutoWCF.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutoWCFClient(EndpointConfiguration endpointConfiguration) : 
                base(ProdutoWCFClient.GetBindingForEndpoint(endpointConfiguration), ProdutoWCFClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutoWCFClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProdutoWCFClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutoWCFClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProdutoWCFClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProdutoWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ListarProdutosResponse> ListarProdutosAsync(NetshoesService.ListarProdutosRequest request)
        {
            return base.Channel.ListarProdutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ListarCategoriasResponse> ListarCategoriasAsync(NetshoesService.ListarCategoriasRequest request)
        {
            return base.Channel.ListarCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ListarMarcasResponse> ListarMarcasAsync(NetshoesService.ListarMarcasRequest request)
        {
            return base.Channel.ListarMarcasAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ListarPrecosResponse> ListarPrecosAsync(NetshoesService.ListarPrecosRequest request)
        {
            return base.Channel.ListarPrecosAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ListarPrecosStepResponse> ListarPrecosStepAsync(NetshoesService.ListarPrecosStepRequest request)
        {
            return base.Channel.ListarPrecosStepAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarDataEnvioPrecosStepResponse> ConfirmarDataEnvioPrecosStepAsync(NetshoesService.ConfirmarDataEnvioPrecosStepRequest request)
        {
            return base.Channel.ConfirmarDataEnvioPrecosStepAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarPrecosStepResponse> ConfirmarPrecosStepAsync(NetshoesService.ConfirmarPrecosStepRequest request)
        {
            return base.Channel.ConfirmarPrecosStepAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoProdutoResponse> ConfirmarRecebimentoProdutoAsync(NetshoesService.ConfirmarRecebimentoProdutoRequest request)
        {
            return base.Channel.ConfirmarRecebimentoProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoCategoriaResponse> ConfirmarRecebimentoCategoriaAsync(NetshoesService.ConfirmarRecebimentoCategoriaRequest request)
        {
            return base.Channel.ConfirmarRecebimentoCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoMarcaResponse> ConfirmarRecebimentoMarcaAsync(NetshoesService.ConfirmarRecebimentoMarcaRequest request)
        {
            return base.Channel.ConfirmarRecebimentoMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoPrecoResponse> ConfirmarRecebimentoPrecoAsync(NetshoesService.ConfirmarRecebimentoPrecoRequest request)
        {
            return base.Channel.ConfirmarRecebimentoPrecoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoProdutoListaResponse> ConfirmarRecebimentoProdutoListaAsync(NetshoesService.ConfirmarRecebimentoProdutoListaRequest request)
        {
            return base.Channel.ConfirmarRecebimentoProdutoListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoCategoriaListaResponse> ConfirmarRecebimentoCategoriaListaAsync(NetshoesService.ConfirmarRecebimentoCategoriaListaRequest request)
        {
            return base.Channel.ConfirmarRecebimentoCategoriaListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoMarcaListaResponse> ConfirmarRecebimentoMarcaListaAsync(NetshoesService.ConfirmarRecebimentoMarcaListaRequest request)
        {
            return base.Channel.ConfirmarRecebimentoMarcaListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.ConfirmarRecebimentoPrecoListaResponse> ConfirmarRecebimentoPrecoListaAsync(NetshoesService.ConfirmarRecebimentoPrecoListaRequest request)
        {
            return base.Channel.ConfirmarRecebimentoPrecoListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.PrecoLojaOnLineResponse> PrecoLojaOnLineAsync(NetshoesService.PrecoLojaOnLineRequest request)
        {
            return base.Channel.PrecoLojaOnLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesService.TipoCompilacaoResponse> TipoCompilacaoAsync(NetshoesService.TipoCompilacaoRequest request)
        {
            return base.Channel.TipoCompilacaoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProdutoWCF))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProdutoWCF))
            {
                return new System.ServiceModel.EndpointAddress("https://187.61.25.11:1003/ProdutoWCF.svc/basicHttpBinding");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProdutoWCFClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProdutoWCF);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProdutoWCFClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProdutoWCF);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProdutoWCF,
        }
    }
}
