FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build 
ARG PAT
WORKDIR /app
COPY . .
ARG PAT="bssye37hfu5k2vouzaejolrf32ivtbagsljud6uhldqqrsfu3qxa"
RUN echo "<?xml version='1.0' encoding='utf-8'?><configuration><packageSources><clear /><add key='Reconhece' value='https://pkgs.dev.azure.com/digidevs/1c19ed26-f31d-428b-89e9-541db3d12dab/_packaging/Reconhece/nuget/v3/index.json' /></packageSources><packageSourceCredentials><Reconhece><add key='Username' value='andre.araujo' /><add key='ClearTextPassword' value='$PAT' /></Reconhece></packageSourceCredentials></configuration>" > NuGet.Config
RUN dotnet restore MsProductIntegrationNovapontocom.csproj
RUN dotnet publish MsProductIntegrationNovapontocom.csproj -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime
# Install cultures (same approach as Alpine SDK image)
RUN apk add --no-cache icu-libs
# Disable the invariant mode (set in base image)
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
WORKDIR /app
COPY --from=build /app/publish /app
ENTRYPOINT ["dotnet", "/app/MsProductIntegrationNovapontocom.dll"]








































