//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetshoesEstoqueService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoEstoqueSolicitadoEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Estoque.Entity")]
    public partial class ProdutoEstoqueSolicitadoEN : object
    {
        
        private int QuantidadeField;
        
        private string SkuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku
        {
            get
            {
                return this.SkuField;
            }
            set
            {
                this.SkuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoEstoqueResumoEN", Namespace="http://schemas.datacontract.org/2004/07/Abacos.Net.Estoque.Entity")]
    public partial class ProdutoEstoqueResumoEN : object
    {
        
        private bool AtendeField;
        
        private string SkuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Atende
        {
            get
            {
                return this.AtendeField;
            }
            set
            {
                this.AtendeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku
        {
            get
            {
                return this.SkuField;
            }
            set
            {
                this.SkuField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NetshoesEstoqueService.IEstoqueWCF")]
    public interface IEstoqueWCF
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstoqueWCF/ConsultarEstoque", ReplyAction="http://tempuri.org/IEstoqueWCF/ConsultarEstoqueResponse")]
        System.Threading.Tasks.Task<NetshoesEstoqueService.ConsultarEstoqueResponse> ConsultarEstoqueAsync(NetshoesEstoqueService.ConsultarEstoqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstoqueWCF/ProdutoEstoqueZerado", ReplyAction="http://tempuri.org/IEstoqueWCF/ProdutoEstoqueZeradoResponse")]
        System.Threading.Tasks.Task<NetshoesEstoqueService.ProdutoEstoqueZeradoResponse> ProdutoEstoqueZeradoAsync(NetshoesEstoqueService.ProdutoEstoqueZeradoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarEstoque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarEstoqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public NetshoesEstoqueService.ProdutoEstoqueSolicitadoEN[] listProdutoEstoqueSolicitado;
        
        public ConsultarEstoqueRequest()
        {
        }
        
        public ConsultarEstoqueRequest(string identificacaoLoja, string chaveIdentificacao, NetshoesEstoqueService.ProdutoEstoqueSolicitadoEN[] listProdutoEstoqueSolicitado)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
            this.listProdutoEstoqueSolicitado = listProdutoEstoqueSolicitado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarEstoqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarEstoqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NetshoesEstoqueService.ProdutoEstoqueResumoEN[] ConsultarEstoqueResult;
        
        public ConsultarEstoqueResponse()
        {
        }
        
        public ConsultarEstoqueResponse(NetshoesEstoqueService.ProdutoEstoqueResumoEN[] ConsultarEstoqueResult)
        {
            this.ConsultarEstoqueResult = ConsultarEstoqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProdutoEstoqueZerado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProdutoEstoqueZeradoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string identificacaoLoja;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string chaveIdentificacao;
        
        public ProdutoEstoqueZeradoRequest()
        {
        }
        
        public ProdutoEstoqueZeradoRequest(string identificacaoLoja, string chaveIdentificacao)
        {
            this.identificacaoLoja = identificacaoLoja;
            this.chaveIdentificacao = chaveIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProdutoEstoqueZeradoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProdutoEstoqueZeradoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] ProdutoEstoqueZeradoResult;
        
        public ProdutoEstoqueZeradoResponse()
        {
        }
        
        public ProdutoEstoqueZeradoResponse(string[] ProdutoEstoqueZeradoResult)
        {
            this.ProdutoEstoqueZeradoResult = ProdutoEstoqueZeradoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IEstoqueWCFChannel : NetshoesEstoqueService.IEstoqueWCF, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EstoqueWCFClient : System.ServiceModel.ClientBase<NetshoesEstoqueService.IEstoqueWCF>, NetshoesEstoqueService.IEstoqueWCF
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EstoqueWCFClient() : 
                base(EstoqueWCFClient.GetDefaultBinding(), EstoqueWCFClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEstoqueWCF.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstoqueWCFClient(EndpointConfiguration endpointConfiguration) : 
                base(EstoqueWCFClient.GetBindingForEndpoint(endpointConfiguration), EstoqueWCFClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstoqueWCFClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EstoqueWCFClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstoqueWCFClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EstoqueWCFClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EstoqueWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NetshoesEstoqueService.ConsultarEstoqueResponse> ConsultarEstoqueAsync(NetshoesEstoqueService.ConsultarEstoqueRequest request)
        {
            return base.Channel.ConsultarEstoqueAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetshoesEstoqueService.ProdutoEstoqueZeradoResponse> ProdutoEstoqueZeradoAsync(NetshoesEstoqueService.ProdutoEstoqueZeradoRequest request)
        {
            return base.Channel.ProdutoEstoqueZeradoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEstoqueWCF))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEstoqueWCF))
            {
                return new System.ServiceModel.EndpointAddress("https://187.61.25.11:1004/EstoqueWCF.svc/basicHttpBinding");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EstoqueWCFClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEstoqueWCF);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EstoqueWCFClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEstoqueWCF);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEstoqueWCF,
        }
    }
}
